### ISSUE TITLE
TypeError after upgrade from D7

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/content_lock#4]
After an upgrade on a site that has Content Lock enabled, I'm seeing this when I try to load the site:

> TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in array_filter() (line 1150 of /var/www/html/modules/contrib/content_lock/content_lock.module).

**Comment by laryn** [comment]
It seems that the update hook never was run. I removed these lines:

```
// TODO The old hook_update_N functions cannot be applied to Backdrop.
function content_lock_update_6200() { }

/**
 * Implements hook_update_last_removed().
 */
function content_lock_update_last_removed() {
  return 6200;
}
```

Then I reset the `schema_version` manually in the database to `99` and ran updates again. The update hook then ran successfully.

**Comment by robertgarrigos** [comment]
Thank @laryn. Where did you remove these lines from? I cannot find them.

**Comment by robertgarrigos** [comment]
Sorry, I see. I actually pulled a request but not made a release. I'll done it later today, after looking at the other issue.

**Comment by robertgarrigos** [comment]
Published a new release with the fix. Thanks.
