### ISSUE TITLE
No token added to Views links when Backdrop is installed in subdirectory

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop-contrib/content_lock#7]
Hello,
I have Backdrop installed in a subdirectory of root (e.g. domain.org/mybackdrop) and received the following PHP Notice with my Views having an edit node link:

> Notice: Undefined offset: 1 in content_lock_preprocess_views_view_field() (line 238 of /home/icpdrobs/data.danubesurvey.org/backdrop/modules/content_lock/content_lock.module).

This is due to the pattern `/href="\/(node\/\d+\/edit)/` in function _content_lock_preprocess_views_view_field_ which does not find any match if the path does not start with '/node', so the _$matches[1]_ triggers the notice (and no token path is defined).

I suggest to change the pattern to `/href=".*\/(node\/\d+\/edit)/`. The same needs to be done for the other pattern in the function.
But there might be a better solution. If not, I can provide a PR if needed.

**Comment by robertgarrigos** [comment]
Thanks, @AlexHoebart-ICPDR, would you like to test the PR?

**Comment by robertgarrigos** [comment]
@AlexHoebart-ICPDR, thanks for your testing. Added the same fix to the line 235.

**Comment by AlexHoebart-ICPDR** [comment]
@robertgarrigos looks good, I think that's it.
